[package]
edition = "2018"
name = "keymoji"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttype = "0.9.2"
simple_logger = "1.13.0"
winit = "0.25.0"
